using System.Text.Json;
using Microsoft.AspNetCore.Mvc;

namespace MyBankApi.Controllers;

[ApiController]
[Route("api/[controller]/[action]")]
public class AdminController : ControllerBase
{
    [HttpGet]
    public async Task<IActionResult> GetAtmsFromJsonFile([FromQuery] string filepath)
    {
        filepath = @"C:\Users\Anton\Downloads\atms1copy.json";
        await using FileStream openStream = System.IO.File.OpenRead(filepath);
        JsonAutogeneratedClass? jsonObject = await JsonSerializer.DeserializeAsync<JsonAutogeneratedClass>(openStream);
        return Ok(jsonObject);
    }

    [HttpGet]
    public async Task<IActionResult> GetAtmsFromBankPage()
    {
        var url = $@"https://belarusbank.by/open-banking/v1.0/atms";
        var httpClient = new HttpClient();
        var response = await httpClient.GetAsync(url);
        JsonAutogeneratedClass? jsonObject = 
            await JsonSerializer.DeserializeAsync<JsonAutogeneratedClass>(await response.Content.ReadAsStreamAsync());
        return Ok(jsonObject?.Data.ATM);
    }
}
