using System.Text.Json;
using AutoMapper;
using DataEntityAndAccessLayer;
using Microsoft.AspNetCore.Mvc;
using ServiceLayer;

namespace MyBankApi.Controllers;

[ApiController]
[Route("api/[controller]")]
public class AdminController : ControllerBase
{
    private readonly IMapper _mapper;

    public AdminController(IMapper mapper)
    {
        _mapper = mapper;
    }

    [HttpGet("getfromfile")]
    public async Task<IActionResult> GetAtmsFromJsonFile([FromQuery] string filepath)
    {
        filepath = @"C:\Users\Anton\Downloads\atms1copy.json";
        await using FileStream openStream = System.IO.File.OpenRead(filepath);
        JsonAutogeneratedClass? jsonObject = await JsonSerializer.DeserializeAsync<JsonAutogeneratedClass>(openStream);
        return Ok(jsonObject);
    }

    [HttpGet("getfrompage")]
    public async Task<IActionResult> GetAtmsFromBankPage()
    {
        var url = $@"https://belarusbank.by/open-banking/v1.0/atms";
        var httpClient = new HttpClient();
        var response = await httpClient.GetAsync(url);
        JsonAutogeneratedClass? jsonObject = 
            await JsonSerializer.DeserializeAsync<JsonAutogeneratedClass>(await response.Content.ReadAsStreamAsync());
        return Ok(jsonObject?.Data.ATM);
    }

    [HttpGet("addtodb")]
    public async Task<IActionResult> AddAtmsFromPageToDatabase([FromServices] BankDbContext context)
    {
        var url = $@"https://belarusbank.by/open-banking/v1.0/atms";
        var httpClient = new HttpClient();
        var response = await httpClient.GetAsync(url);
        JsonAutogeneratedClass? jsonObject =
            await JsonSerializer.DeserializeAsync<JsonAutogeneratedClass>(await response.Content.ReadAsStreamAsync());
        var service = new AtmService(context, _mapper);
        await service.AddAtmsToDb(jsonObject);
        return Ok();
    }
}
