public class JsonAutogeneratedClass
{
    public Data Data { get; set; }
}

public class Data
{
    public ATM[] ATM { get; set; }
}

public class ATM
{
    public string atmId { get; set; }
    public string type { get; set; }
    public string baseCurrency { get; set; }
    public string currency { get; set; }
    public string[] cards { get; set; }
    public string currentStatus { get; set; }
    public Address Address { get; set; }
    public Service[] Services { get; set; }
    public Availability Availability { get; set; }
    public Contactdetails ContactDetails { get; set; }
}

public class Address
{
    public string streetName { get; set; }
    public string buildingNumber { get; set; }
    public string townName { get; set; }
    public string countrySubDivision { get; set; }
    public string country { get; set; }
    public string addressLine { get; set; }
    public string description { get; set; }
    public Geolocation Geolocation { get; set; }
}

public class Geolocation
{
    public Geographiccoordinates GeographicCoordinates { get; set; }
}

public class Geographiccoordinates
{
    public string latitude { get; set; }
    public string longitude { get; set; }
}

public class Availability
{
    public bool access24Hours { get; set; }
    public bool isRestricted { get; set; }
    public bool sameAsOrganization { get; set; }
    public Standardavailability StandardAvailability { get; set; }
}

public class Standardavailability
{
    public Day[] Day { get; set; }
}

public class Day
{
    public string dayCode { get; set; }
    public string openingTime { get; set; }
    public string closingTime { get; set; }
    public Break Break { get; set; }
}

public class Break
{
    public string breakFromTime { get; set; }
    public string breakToTime { get; set; }
}

public class Contactdetails
{
    public string phoneNumber { get; set; }
}

public class Service
{
    public string serviceType { get; set; }
    public string description { get; set; }
}
