using DataEntityAndAccessLayer;
using DataEntityAndAccessLayer.Entities.Atm;
using Microsoft.EntityFrameworkCore;
using ServiceLayer.Mapping;

namespace ServiceLayer;

public class AtmRepositoryService
{
    private readonly BankDbContext _context;

    public AtmRepositoryService(BankDbContext context)
    {
        _context = context;
    }

    public async Task<List<Atm>> GetAllAtms()
    {
        return await _context.Atms
            .Include(atm => atm.AtmType)
            .Include(atm => atm.AtmAvailability)
            .ThenInclude(av => av.AtmStandardAvailability)
            .ThenInclude(stav => stav.Days)
            .Include(atm => atm.AtmCardSchemes)
            .Include(atm => atm.AtmServices)
            .Include(atm => atm.ContactDetails)
            .AsNoTracking()
            .ToListAsync();
    }

    public async Task AddAtmsToDb(JsonAutogeneratedClass data)
    {
        var atmsArray = data.Data.ATM;
        var atmsMapToDb = new Atm[atmsArray.Length];
        var converter = new AtmMappingHelper(_context);

        for (int i = 0; i < atmsArray.Length; i++)
        {
            var jsonObj = atmsArray[i];
            var atmToDb = await converter.ConvertToEntity(jsonObj);
            foreach (var atmService in atmToDb.AtmServices)
            {
                atmService.Atms.Add(atmToDb);
            }

            foreach (var cardScheme in atmToDb.AtmCardSchemes)
            {
                cardScheme.Atms.Add(atmToDb);
            }

            atmToDb.AtmType?.Atms.Add(atmToDb);

            atmsMapToDb[i] = atmToDb;
        }

        await _context.Atms.AddRangeAsync(atmsMapToDb);
        await _context.SaveChangesAsync();
    }
}
